### ISSUE TITLE
Include `boundary=disputed` in `boundaries`

### ISSUE THREAD

**Issue by yetzt** [shortbread-tiles/shortbread-docs#1]
For my use case it's important to display disputed borders in a different style from undisputed borders, therefore i propose to extend the `boundaries` layer by a boolean `disputed` property based on the [`boundary=disputed`](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Ddisputed) tag.

**Comment by woodpeck** [comment]
This might warrant a closer look at the data since a disputed boundary might also be tagged boundary=disputed (instead of boundary=administrative, disputed=yes). Simply introducing a disputed column might catch only a fraction of actual disputed boundaries.

**Comment by riQQ** [comment]
This issue is completed via d74537ee8a4bd119d3c3cd0c9eaebaf31e1e4481 and the PR linked in this commit, right?

**Comment by yetzt** [comment]
i believe so, though the pull request is now [here](https://github.com/shortbread-tiles/shortbread-tilemaker/pull/11) and the commit [there](https://github.com/shortbread-tiles/shortbread-tilemaker/commit/1dabbed06ddeaf1cb30ab65c37afbc32b8dad216)
