### ISSUE TITLE
service=driveway not rendered

### ISSUE THREAD

**Issue by matheusgomesms** [shortbread-tiles/shortbread-docs#51]
First of all, congrats for the awesome work!

Not sure if this is the proper place (please close issue if not), but:

`highway=service` + `service=driveway` is not rendered. `service=parking_aisle` (with half of use) and `service=emergency_access` are rendered, though.

Also, all of them are rendered equally as `highway=service` (without subtag). Not sure if intended behavior, but in Carto its subtags (`service=*`) are rendered with thinner lines, compared to features with `highway=service` only.

Didn't check other service tags.

**Comment by systemed** [comment]
This is not an issue with the Shortbread schema. [The schema](https://shortbread-tiles.org/schema/1.0/#layer-streets) includes a `service` value, which is the OSM value for the `service=` tag. Please open the issue against whatever implementation you're referring to.
