### ISSUE TITLE
The value "artwork" is in the wrong place

### ISSUE THREAD

**Issue by SomeoneElseOSM** [shortbread-tiles/shortbread-docs#54]
Currently https://github.com/shortbread-tiles/shortbread-docs/blob/main/shortbread-website/content/schema/1.0.md contains:

    {{< tag historic artwork >}}

Based on common tagging, I'd expect this to be in "tourism" rather than "historic".  See https://taginfo.openstreetmap.org/tags/historic=artwork#overview and https://taginfo.openstreetmap.org/tags/tourism=artwork#overview .

Once the schema has changed https://github.com/shortbread-tiles/shortbread-tilemaker/blob/main/process.lua#L64 will also need to change.

**Comment by joto** [comment]
This has been fixed in the specs and I also fixed it in shortbread-tilemaker.
