### ISSUE TITLE
Guidelines for customizing/extending Shortbread

### ISSUE THREAD

**Issue by pka** [shortbread-tiles/shortbread-docs#56]
I've prepared slides for my SotM Euro talk "[Customizing Shortbread vector tiles](https://cfp.openstreetmap.org.pl/state-of-the-map-europe-2024/talk/LVVUFH/)":  [slides](https://pka.github.io/customizing-shortbread-vector-tiles/) ([source](https://github.com/pka/customizing-shortbread-vector-tiles))

My goal was to collect material which can be added to shortbread-docs and formulate some guidelines for extending Shortbread. A few slides will probably only land in the documentation and maybe there is more to say for guiding people?

@systemed @joto  @pnorman: Corrections/input on the tilemaker, osm2pgsql and tilekiln chapters are welcome.

**Comment by pka** [comment]
See #57

**Comment by pnorman** [comment]
I thought we had a still open issue from someone who wanted guidance on how to extend shortbread without colliding with future layers or attribute names. Does anyone know of that, or is this issue the only one and I'm not remembering correctly?
